# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YCSg8VKwMvN5Nx9PLe1ntVAgaRX94u0J
"""

#Code by K.A. Raja Babu
#May 19, 2021
#Drawing two concentric circles

import numpy as np
import matplotlib.pyplot as plt
import subprocess
import shlex
from coeffs import * #refered from G.V.V sir's code

#centre and radius of circles
O=np.array([-1,2])
r1=2.5
r2=4

#point on circles
A1=np.array([O[0]+r1,O[1]])
A2=np.array([O[0],O[1]+r2])

#Generating all lines
x_OA1 = line_gen(O,A1)
x_OA2 = line_gen(O,A2)

#Plotting all lines
plt.plot(x_OA1[0,:],x_OA1[1,:],label='$r=2.5$')
plt.plot(x_OA2[0,:],x_OA2[1,:],label='$r=4$')

#plotting first circle of radius 2.5
len1=100
theta1 = np.linspace(0,2*np.pi,len1)
x_circ1 = np.zeros((2,len1))
x_circ1[0,:] = r1*np.cos(theta1)
x_circ1[1,:] = r1*np.sin(theta1)
x_circ1 = (x_circ1.T + O).T
plt.plot(x_circ1[0,:],x_circ1[1,:],label='$circle with (r=2.5)$')

#plotting second circle of radius 4
len2=100
theta2 = np.linspace(0,2*np.pi,len2)
x_circ2 = np.zeros((2,len2))
x_circ2[0,:] = r2*np.cos(theta2)
x_circ2[1,:] = r2*np.sin(theta2)
x_circ2 = (x_circ2.T + O).T
plt.plot(x_circ2[0,:],x_circ2[1,:],label='$circle with (r=4)$')


#plotting points
plt.plot(O[0], O[1], 'o')
plt.text(O[0] * (1 + 0.001), O[1] * (1 - 0.001) , 'O')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(bbox_to_anchor=(1.05, 1),loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()