# -*- coding: utf-8 -*-
"""Assignment13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxci9wL68X4Ft48HRWyH6zwxwpSUpBvV
"""

#Code by K.A. Raja Babu
#June 24,2021

import numpy as np
import matplotlib.pyplot as plt

def bayes_theorem(p_e1,p_e2,p_xgiven_e1,p_xgiven_e2):
	p_x= p_e1*p_xgiven_e1 + p_e2*p_xgiven_e2
	numerator1 = p_e1*p_xgiven_e1
	p_e1given_x=numerator1/p_x
	return p_e1given_x

#Probability that person actually has disease
p_1= 0.001
#Probability that person actually does not have disease
p_2= 1-p_1
#Probability that test result is positive provided person actually has disease
p_correct_1=0.99
#Probability that test report is positive provided person actually does not have disease
p_correct_2= 0.005

#Probability that person has disease provided his test result is positive
prob= bayes_theorem(p_1,p_2,p_correct_1, p_correct_2)

print(prob)