# -*- coding: utf-8 -*-
"""Assignment15_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11qv40B4HSbGoTakpnwVgDU2Xs9v3-767
"""

#Code by K.A. Raja Babu
#July 07, 2021

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating and plotting line x+y = 4
A=np.array([-1,5])
B=np.array([5,-1])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='x+y=4')

#Generating and plotting line x = 0
C=np.array([0,-1])
D=np.array([0,5])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='x=0')

#Generating and plotting line y=0
E=np.array([-1,0])
F=np.array([5,0])
EF=line_gen(E,F)
plt.plot(EF[0,:],EF[1,:],label='y=0')

#Shading Required Region
x1=[0,0,4]
y1=[0,4,0]
plt.fill(x1,y1)

#Labelling points
plt.plot(0,0,'o',color='r')
plt.text(0.2,-0.4,'A(0,0)')
plt.plot(0,4,'o',color='r')
plt.text(0.2,4,'B(0,4)')
plt.plot(4,0,'o',color='r')
plt.text(4,0.2,'C(4,0)')

plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() 
plt.axis('equal')