# -*- coding: utf-8 -*-
"""Assignment15_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w02aX1wFmrqmKbW3dzveoJvBnGCQtWUY
"""

#Code by K.A. Raja Babu
#July 07,2021

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1,1],[-1,0],[0,-1]]).T
b = np.array([4,0,0]).reshape((3,-1 ))
c = np.array([3,4])

x = Variable((2,1),nonneg = True)

f = c@x
obj = Maximize(f)
# Constraints
constraints = [A.T@x <= b]
Problem(obj, constraints).solve()

print("Maximum_value: " ,(f.value))
print("attained at: ",(x.value))