# -*- coding: utf-8 -*-
"""ChallengeProblem4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lbW3T9SwCX_NLLaMBe6wEsNRVuVL-SM5
"""

#Code by K.A. Raja Babu
#June 20, 2021

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np


#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#creating x,y for 3D plotting
xx, yy = np.meshgrid(range(10), range(10))


#setting up plot
fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')

#Points
A = np.array([-0.5,4.5,5]).reshape((3,1))
B = np.array([4,-3,-1]).reshape((3,1))

#Generating all lines
x_AB = line_gen(A,B)
#plotting line
plt.plot(x_AB[0,:],x_AB[1,:],x_AB[2,:],color='g',label='Given line')

#defining planes:  n.T * x = c 
n1 = np.array([1,-1,2]).reshape((3,1))
c1 = 5
n2 = np.array([3,1,1]).reshape((3,1))
c2= 6
 
#corresponding z for planes
z1 = (c1-n1[0]*xx-n1[1]*yy)/(n1[2])
z2 = (c2-n2[0]*xx-n2[1]*yy)/(n2[2])
 
#plotting planes
Plane1=ax.plot_surface(xx,z1,yy, color='b',alpha=0.25,label='Plane (1 -1 2)x=5')
Plane2=ax.plot_surface(xx,z2,yy, color='r',alpha=0.25,label='Plane (3 1 1)x=6')
Plane1._facecolors2d=Plane1._facecolors3d
Plane1._edgecolors2d=Plane1._edgecolors3d
Plane2._facecolors2d=Plane2._facecolors3d
Plane2._edgecolors2d=Plane2._edgecolors3d

#Plotting and labelling point A
ax.scatter(1,2,3,'o')
ax.text(-2.7,2.5,2.1, "A(1,2,3)")

plt.xlabel('$x$');plt.ylabel('$y$')
plt.grid()
plt.legend(loc='best')


plt.show()