# -*- coding: utf-8 -*-
"""Assignment9_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jhIVjXR--6eql_6nE-WWJNNE_dzekDfJ
"""

#Code by K.A. Raja Babu
#June 14, 2021

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Path of bullet
x = np.linspace(0,22.76,23)
p=np.poly1d([-0.124,2.823,0])
for i in range(len(x)):
    y=p(x)

#Initial point of bullet
A=np.array([0,0])

#Initial point of plane
B=np.array([0,15])

#Generating and Plotting line AB
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:])

#Bullet and plane hitting point
C=np.array([8.449,15])

#Generating and Plotting line BC
BC=line_gen(B,C)
plt.plot(BC[0,:],BC[1,:])

#Generating and plotting vector v_b
V=np.array([2,5])
AV=line_gen(A,V)
plt.plot(AV[0,:],AV[1,:])
plt.annotate(s='', xy=(2,5), xytext=(2.3,6), arrowprops=dict(arrowstyle='<-'))

#Generating and plotting vector v_p
P=np.array([3,15])
BP=line_gen(B,P)
plt.plot(BP[0,:],BP[1,:])
plt.annotate(s='', xy=(0,15), xytext=(4,15), arrowprops=dict(arrowstyle='<-'))

#drawing arc
r=2
theta = np.linspace(1.230,1.570,50)
x1 = r*np.cos(theta)
y1 = r*np.sin(theta)
plt.plot(x1,y1)

#Plotting parabolic path of bullet
plt.plot(x,y,'--',label='Path of bullet')

#Labelling points
plt.plot(0,0,'o',label='Bullet Starting Pt.')
plt.text(-0.9,-0.3,'A')
plt.plot(0,15,'o',label='Plane Starting Pt.')
plt.text(-0.9,15.5,'B')
plt.plot(8.449,15,'o',label='Hitting Pt.')
plt.text(8.2,15.5,'C')
plt.plot(11.38,16,'o',label='Max. Height')
plt.text(11.2,16.2,'D')
plt.text(0.2,3,'$ \u03B8 $')
plt.text(2,4,'$v_b$')
plt.text(3,14,'$v_p$')

plt.xlabel('$Distance$')
plt.ylabel('$Height$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')