# -*- coding: utf-8 -*-
"""Assignment14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aHaRl-HMGWRpozCm5YhEOHs3KudJ8y3
"""

#PMF of X
#Code by K.A. Raja Babu
#July 05 ,2021

from scipy.stats import binom
import matplotlib.pyplot as plt

#Defining input values
n=3
p=0.5
k=list(range(n+1))

#Calculating pmf
dist=[binom.pmf(k1,n,p) for k1 in k]

#Printing pmf values
print("k \t p(k)")
for i in range(n+1) :
  print(str(k[i]) + "\t" + str(dist[i]))

#Plotting the pmf graph
plt.stem(k,dist,use_line_collection = True)
plt.xlabel("$k$")
plt.ylabel("$p_{X}(k)$")
plt.title("PMF of $X$")
plt.show()