# -*- coding: utf-8 -*-
"""Assignment16_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1717QbWZPm-Fv1laEkZSiEivDwz4cqZJe
"""

#Code by K.A. Raja Babu
#July 12, 2021

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#creating x,y for 3D plotting
xx, yy = np.meshgrid(range(2), range(2))

#setting up plot
fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')


A = np.array([0,1,0]).reshape((3,1))
B = np.array([0,1,0.04]).reshape((3,1))
x_AB = line_gen(A,B)
C = np.array([1,0,0]).reshape((3,1))
D = np.array([1,0,0.16]).reshape((3,1))
x_CD = line_gen(C,D)
E = np.array([0,0,0]).reshape((3,1))
F = np.array([0,0,0.36]).reshape((3,1))
x_EF = line_gen(E,F)
G = np.array([1,1,0]).reshape((3,1))
H = np.array([1,1,0.64]).reshape((3,1))
x_GH = line_gen(G,H)

plt.plot(x_AB[0,:],x_AB[1,:],x_AB[2,:])
plt.plot(x_CD[0,:],x_CD[1,:],x_CD[2,:])
plt.plot(x_EF[0,:],x_EF[1,:],x_EF[2,:])
plt.plot(x_GH[0,:],x_GH[1,:],x_GH[2,:])

ax.scatter(B[0],B[1],B[2],'o')
ax.scatter(D[0],D[1],D[2],'o')
ax.scatter(F[0],F[1],F[2],'o')
ax.scatter(H[0],H[1],H[2],'o')
ax.text(0,1,0.09, "0.04")
ax.text(1,0,0.22, "0.16")
ax.text(0,0,0.42, "0.36")
ax.text(0.8,1,0.64, "0.64")

ax.set_xticklabels(['','0','','','','','1'])
ax.set_yticklabels(['','0','','','','','1'])
plt.xlabel('$x$');plt.ylabel('$y$');
plt.title("Joint PMF of X and Y")

plt.show()