# -*- coding: utf-8 -*-
"""Assignment16_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Io8xl1rxBpxBk_CxFvxMRh5s5n56_3jD
"""

#Code by K.A. Raja Babu
#July 11 ,2021

import matplotlib.pyplot as plt

a = {'0':0.4, '1':0.8}
x = list(a.keys())
y = list(a.values())
plt.grid()
plt.stem(x,y,use_line_collection = True)
plt.xlabel("$x$")
plt.ylabel("$p_{X}(x)$")
plt.title("PMF of $X$")
plt.show()