# -*- coding: utf-8 -*-
"""Assignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XLIpqIJ2JMZPhyYy-iLA5RWcqcn02nue
"""

#Code by K.A. Raja Babu
#June 01, 2021

import numpy as np
import matplotlib.pyplot as plt
from coeffs import * #referred from G.V.V sir's Code

#Defining coordinates
y = np.linspace(-15,15,100)
p=np.poly1d([1/8,0,0])
for i in range(len(y)):
    x=p(y)

#Plotting directrix
O1=np.array([-2,-4])
O2=np.array([-2,4])
dir=line_gen(O1,O2)
plt.plot(dir[0,:],dir[1,:],label='$x=-2$')
plt.annotate(s='',xy=(-2,4), xytext=(-2,4.5), arrowprops=dict(arrowstyle='<-'))
plt.annotate(s='', xy=(-2,-4), xytext=(-2,-4.5), arrowprops=dict(arrowstyle='<-'))

#Plotting latus rectum
L1=np.array([2,4])
L2=np.array([2,-4])
latus=line_gen(L1,L2)
plt.plot(latus[0,:],latus[1,:],label='$x=2$')

#Plotting axis
A1=np.array([-6,0])
A2=np.array([6.2,0])
axis=line_gen(A1,A2)
plt.plot(axis[0,:],axis[1,:],label='$y=0$',color='blue')
plt.annotate(s='',xy=(-6,0), xytext=(-6.5,0), arrowprops=dict(arrowstyle='<-'))
plt.annotate(s='', xy=(6.2,0), xytext=(6.7,0), arrowprops=dict(arrowstyle='<-'))

#Plotting points
plt.plot(x,y,label='$y^2=8x$')
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.plot(2,0,'o')
plt.text(2.2,-0.6,'F')
plt.plot(0,0,'o')
plt.text(-0.5,-0.5,'c')
plt.plot(2,4,'o')
plt.text(1.6,4.2,'M')
plt.plot(2,-4,'o')
plt.text(1.5,-4.4,'N')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.xlim([-1,1])  
plt.ylim([-5,5])

plt.show()